

# action.yml
name: Smurf Action
description: A custom GitHub Action that runs the Smurf CLI tool with Docker.
author: Your Name
inputs:
  docker_username:
    description: "Docker Hub username"
    required: false
  docker_password:
    description: "Docker Hub password"
    required: false
    secret: true

runs:
  using: "docker"
  image: "Dockerfile"
  # args:
  #   - ${{ inputs.args }}

branding:
  icon: "package"
  color: "blue"
